# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-04 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='username',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
