# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-04 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_githubuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='blog',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='following',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='public_posts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
