# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-04 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180904_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
