# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-04 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180904_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 4, 7, 13, 34, 39214)),
        ),
    ]
